/*
* Generated file
*
* Generated from: yang module name: odl-sal-dom-rpc-remote-cfg yang module local name: remote-rpc-client
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:25:17 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.remote.rpc;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc?revision=2013-10-28)remote-rpc-client", osgiRegistrationType = org.opendaylight.controller.sal.connector.remoterpc.RemoteRpcClient.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc", revision = "2013-10-28", localName = "remote-rpc-client")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc", revision = "2013-10-28", name = "odl-sal-dom-rpc-remote-cfg")

public interface RemoteRpcClientServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
