/*
* Generated file
*
* Generated from: yang module name: odl-sal-dom-rpc-remote-cfg yang module local name: remote-zeromq-rpc-server
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:25:17 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.remote.rpc;
public interface ZeroMQServerModuleMXBean {
    public java.lang.Integer getPort();

    public void setPort(java.lang.Integer port);

    public javax.management.ObjectName getDomBroker();

    public void setDomBroker(javax.management.ObjectName domBroker);

}
