/*
* Generated file
*
* Generated from: yang module name: opendaylight-sal-binding-broker-impl yang module local name: binding-data-compatible-broker
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:25:01 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.binding.impl;
@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(revision = "2013-10-28", name = "opendaylight-sal-binding-broker-impl", namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding:impl")

public abstract class AbstractForwardedCompatibleDataBrokerImplModule implements org.opendaylight.controller.config.spi.Module,org.opendaylight.controller.config.yang.md.sal.binding.impl.ForwardedCompatibleDataBrokerImplModuleMXBean,org.opendaylight.controller.config.yang.md.sal.binding.DataBrokerServiceServiceInterface,org.opendaylight.controller.config.yang.md.sal.binding.DataProviderServiceServiceInterface {
    private static final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(org.opendaylight.controller.config.yang.md.sal.binding.impl.AbstractForwardedCompatibleDataBrokerImplModule.class);

    //attributes start

    public static final org.opendaylight.controller.config.api.JmxAttribute domAsyncBrokerJmxAttribute = new org.opendaylight.controller.config.api.JmxAttribute("DomAsyncBroker");
    private javax.management.ObjectName domAsyncBroker; // mandatory

    public static final org.opendaylight.controller.config.api.JmxAttribute bindingMappingServiceJmxAttribute = new org.opendaylight.controller.config.api.JmxAttribute("BindingMappingService");
    private javax.management.ObjectName bindingMappingService; // mandatory

    //attributes end

    private final AbstractForwardedCompatibleDataBrokerImplModule oldModule;
    private final java.lang.AutoCloseable oldInstance;
    private java.lang.AutoCloseable instance;
    private final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;
    private final org.opendaylight.controller.config.api.ModuleIdentifier identifier;
    @Override
    public org.opendaylight.controller.config.api.ModuleIdentifier getIdentifier() {
        return identifier;
    }

    public AbstractForwardedCompatibleDataBrokerImplModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier,org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.identifier = identifier;
        this.dependencyResolver = dependencyResolver;
        this.oldInstance=null;
        ;this.oldModule=null;
    }

    public AbstractForwardedCompatibleDataBrokerImplModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier,org.opendaylight.controller.config.api.DependencyResolver dependencyResolver,AbstractForwardedCompatibleDataBrokerImplModule oldModule,java.lang.AutoCloseable oldInstance) {
        this.identifier = identifier;
        this.dependencyResolver = dependencyResolver;
        this.oldModule = oldModule;
        this.oldInstance = oldInstance;
    }

    @Override
    public void validate() {
        dependencyResolver.validateDependency(org.opendaylight.controller.config.yang.md.sal.dom.BrokerServiceInterface.class, domAsyncBroker, domAsyncBrokerJmxAttribute);dependencyResolver.validateDependency(org.opendaylight.controller.config.yang.md.sal.binding.impl.BindingIndependentMappingServiceServiceInterface.class, bindingMappingService, bindingMappingServiceJmxAttribute);
        customValidation();
    }

    protected void customValidation() {
    }

    private org.opendaylight.controller.sal.core.api.Broker domAsyncBrokerDependency;
    protected final org.opendaylight.controller.sal.core.api.Broker getDomAsyncBrokerDependency(){
        return domAsyncBrokerDependency;
    }private org.opendaylight.yangtools.yang.data.impl.codec.BindingIndependentMappingService bindingMappingServiceDependency;
    protected final org.opendaylight.yangtools.yang.data.impl.codec.BindingIndependentMappingService getBindingMappingServiceDependency(){
        return bindingMappingServiceDependency;
    }

    @Override
    public final java.lang.AutoCloseable getInstance() {
        if(instance==null) {
            domAsyncBrokerDependency = dependencyResolver.resolveInstance(org.opendaylight.controller.sal.core.api.Broker.class, domAsyncBroker, domAsyncBrokerJmxAttribute);bindingMappingServiceDependency = dependencyResolver.resolveInstance(org.opendaylight.yangtools.yang.data.impl.codec.BindingIndependentMappingService.class, bindingMappingService, bindingMappingServiceJmxAttribute);if(oldInstance!=null && canReuseInstance(oldModule)) {
                instance = reuseInstance(oldInstance);
            } else {
                if(oldInstance!=null) {
                    try {
                        oldInstance.close();
                    } catch(Exception e) {
                        logger.error("An error occurred while closing old instance " + oldInstance, e);
                    }
                }
                instance = createInstance();
                if (instance == null) {
                    throw new IllegalStateException("Error in createInstance - null is not allowed as return value");
                }
            }
        }
        return instance;
    }
    public abstract java.lang.AutoCloseable createInstance();

    public boolean canReuseInstance(AbstractForwardedCompatibleDataBrokerImplModule oldModule){
        // allow reusing of old instance if no parameters was changed
        return isSame(oldModule);
    }

    public java.lang.AutoCloseable reuseInstance(java.lang.AutoCloseable oldInstance){
        // implement if instance reuse should be supported. Override canReuseInstance to change the criteria.
        return oldInstance;
    }

    public boolean isSame(AbstractForwardedCompatibleDataBrokerImplModule other) {
        if (other == null) {
            throw new IllegalArgumentException("Parameter 'other' is null");
        }
        if (domAsyncBrokerDependency != other.domAsyncBrokerDependency) { // reference to dependency must be same
            return false;
        }
        if (bindingMappingServiceDependency != other.bindingMappingServiceDependency) { // reference to dependency must be same
            return false;
        }

        return true;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AbstractForwardedCompatibleDataBrokerImplModule that = (AbstractForwardedCompatibleDataBrokerImplModule) o;
        return identifier.equals(that.identifier);
    }

    @Override
    public int hashCode() {
        return identifier.hashCode();
    }

    // getters and setters
    @Override
    public javax.management.ObjectName getDomAsyncBroker() {
        return domAsyncBroker;
    }

    @Override
    @org.opendaylight.controller.config.api.annotations.RequireInterface(value = org.opendaylight.controller.config.yang.md.sal.dom.BrokerServiceInterface.class)
    public void setDomAsyncBroker(javax.management.ObjectName domAsyncBroker) {
        this.domAsyncBroker = domAsyncBroker;
    }

    @Override
    public javax.management.ObjectName getBindingMappingService() {
        return bindingMappingService;
    }

    @Override
    @org.opendaylight.controller.config.api.annotations.RequireInterface(value = org.opendaylight.controller.config.yang.md.sal.binding.impl.BindingIndependentMappingServiceServiceInterface.class)
    public void setBindingMappingService(javax.management.ObjectName bindingMappingService) {
        this.bindingMappingService = bindingMappingService;
    }

}
