/*
* Generated file
*
* Generated from: yang module name: opendaylight-sal-binding-broker-impl yang module local name: binding-data-compatible-broker
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:25:01 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.binding.impl;
public interface ForwardedCompatibleDataBrokerImplModuleMXBean {
    public javax.management.ObjectName getDomAsyncBroker();

    public void setDomAsyncBroker(javax.management.ObjectName domAsyncBroker);

    public javax.management.ObjectName getBindingMappingService();

    public void setBindingMappingService(javax.management.ObjectName bindingMappingService);

}
