/*
* Generated file
*
* Generated from: yang module name: toaster-provider-impl yang module local name: toaster-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:25:30 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.toaster_provider.impl;
public interface ToasterProviderModuleMXBean {
    public javax.management.ObjectName getNotificationService();

    public void setNotificationService(javax.management.ObjectName notificationService);

    public javax.management.ObjectName getRpcRegistry();

    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

}
