/*
* Generated file
*
* Generated from: yang module name: opendaylight-sal-dom-broker-impl yang module local name: dom-broker-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:24:54 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.dom.impl;
@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(revision = "2013-10-28", name = "opendaylight-sal-dom-broker-impl", namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom:impl")

public abstract class AbstractDomBrokerImplModule implements org.opendaylight.controller.config.spi.Module,org.opendaylight.controller.config.yang.md.sal.dom.impl.DomBrokerImplModuleMXBean,org.opendaylight.controller.config.yang.md.sal.dom.BrokerServiceInterface,org.opendaylight.controller.config.api.RuntimeBeanRegistratorAwareModule {
    private static final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(org.opendaylight.controller.config.yang.md.sal.dom.impl.AbstractDomBrokerImplModule.class);

    //attributes start

    public static final org.opendaylight.controller.config.api.JmxAttribute asyncDataBrokerJmxAttribute = new org.opendaylight.controller.config.api.JmxAttribute("AsyncDataBroker");
    private javax.management.ObjectName asyncDataBroker; // optional

    public static final org.opendaylight.controller.config.api.JmxAttribute dataStoreJmxAttribute = new org.opendaylight.controller.config.api.JmxAttribute("DataStore");
    private javax.management.ObjectName dataStore; // optional

    //attributes end

    private final AbstractDomBrokerImplModule oldModule;
    private final java.lang.AutoCloseable oldInstance;
    private java.lang.AutoCloseable instance;
    private final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;
    private final org.opendaylight.controller.config.api.ModuleIdentifier identifier;
    @Override
    public org.opendaylight.controller.config.api.ModuleIdentifier getIdentifier() {
        return identifier;
    }

    public AbstractDomBrokerImplModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier,org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.identifier = identifier;
        this.dependencyResolver = dependencyResolver;
        this.oldInstance=null;
        ;this.oldModule=null;
    }

    public AbstractDomBrokerImplModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier,org.opendaylight.controller.config.api.DependencyResolver dependencyResolver,AbstractDomBrokerImplModule oldModule,java.lang.AutoCloseable oldInstance) {
        this.identifier = identifier;
        this.dependencyResolver = dependencyResolver;
        this.oldModule = oldModule;
        this.oldInstance = oldInstance;
    }

    private org.opendaylight.controller.config.yang.md.sal.dom.impl.DomBrokerImplRuntimeRegistrator rootRuntimeBeanRegistratorWrapper;

    public org.opendaylight.controller.config.yang.md.sal.dom.impl.DomBrokerImplRuntimeRegistrator getRootRuntimeBeanRegistratorWrapper(){
        return rootRuntimeBeanRegistratorWrapper;
    }

    @Override
    public void setRuntimeBeanRegistrator(org.opendaylight.controller.config.api.runtime.RootRuntimeBeanRegistrator rootRuntimeRegistrator){
        this.rootRuntimeBeanRegistratorWrapper = new org.opendaylight.controller.config.yang.md.sal.dom.impl.DomBrokerImplRuntimeRegistrator(rootRuntimeRegistrator);
    }

    @Override
    public void validate() {

        customValidation();
    }

    protected void customValidation() {
    }

    private org.opendaylight.controller.md.sal.dom.api.DOMDataBroker asyncDataBrokerDependency;
    protected final org.opendaylight.controller.md.sal.dom.api.DOMDataBroker getAsyncDataBrokerDependency(){
        return asyncDataBrokerDependency;
    }private org.opendaylight.controller.sal.core.api.data.DataStore dataStoreDependency;
    protected final org.opendaylight.controller.sal.core.api.data.DataStore getDataStoreDependency(){
        return dataStoreDependency;
    }

    @Override
    public final java.lang.AutoCloseable getInstance() {
        if(instance==null) {
            if (asyncDataBroker!=null) {
                asyncDataBrokerDependency = dependencyResolver.resolveInstance(org.opendaylight.controller.md.sal.dom.api.DOMDataBroker.class, asyncDataBroker, asyncDataBrokerJmxAttribute);;
            }if (dataStore!=null) {
                dataStoreDependency = dependencyResolver.resolveInstance(org.opendaylight.controller.sal.core.api.data.DataStore.class, dataStore, dataStoreJmxAttribute);;
            }if(oldInstance!=null && canReuseInstance(oldModule)) {
                instance = reuseInstance(oldInstance);
            } else {
                if(oldInstance!=null) {
                    try {
                        oldInstance.close();
                    } catch(Exception e) {
                        logger.error("An error occurred while closing old instance " + oldInstance, e);
                    }
                }
                instance = createInstance();
                if (instance == null) {
                    throw new IllegalStateException("Error in createInstance - null is not allowed as return value");
                }
            }
        }
        return instance;
    }
    public abstract java.lang.AutoCloseable createInstance();

    public boolean canReuseInstance(AbstractDomBrokerImplModule oldModule){
        // allow reusing of old instance if no parameters was changed
        return isSame(oldModule);
    }

    public java.lang.AutoCloseable reuseInstance(java.lang.AutoCloseable oldInstance){
        // implement if instance reuse should be supported. Override canReuseInstance to change the criteria.
        return oldInstance;
    }

    public boolean isSame(AbstractDomBrokerImplModule other) {
        if (other == null) {
            throw new IllegalArgumentException("Parameter 'other' is null");
        }
        if (asyncDataBrokerDependency != other.asyncDataBrokerDependency) { // reference to dependency must be same
            return false;
        }
        if (dataStoreDependency != other.dataStoreDependency) { // reference to dependency must be same
            return false;
        }

        return true;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AbstractDomBrokerImplModule that = (AbstractDomBrokerImplModule) o;
        return identifier.equals(that.identifier);
    }

    @Override
    public int hashCode() {
        return identifier.hashCode();
    }

    // getters and setters
    @Override
    public javax.management.ObjectName getAsyncDataBroker() {
        return asyncDataBroker;
    }

    @Override
    @org.opendaylight.controller.config.api.annotations.RequireInterface(value = org.opendaylight.controller.config.yang.md.sal.dom.DOMDataBrokerServiceInterface.class)
    public void setAsyncDataBroker(javax.management.ObjectName asyncDataBroker) {
        this.asyncDataBroker = asyncDataBroker;
    }

    @Override
    public javax.management.ObjectName getDataStore() {
        return dataStore;
    }

    @Override
    @org.opendaylight.controller.config.api.annotations.RequireInterface(value = org.opendaylight.controller.config.yang.md.sal.dom.DataStoreServiceInterface.class)
    public void setDataStore(javax.management.ObjectName dataStore) {
        this.dataStore = dataStore;
    }

}
