/*
* Generated file
*
* Generated from: yang module name: opendaylight-sal-dom-broker-impl yang module local name: dom-broker-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:24:54 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.dom.impl;
public interface DomBrokerImplModuleMXBean {
    public javax.management.ObjectName getAsyncDataBroker();

    public void setAsyncDataBroker(javax.management.ObjectName asyncDataBroker);

    public javax.management.ObjectName getDataStore();

    public void setDataStore(javax.management.ObjectName dataStore);

}
