/*
* Generated file
*
* Generated from: yang module name: opendaylight-sal-dom-broker-impl yang module local name: dom-inmemory-data-broker
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:24:54 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.dom.impl;
public interface DomInmemoryDataBrokerModuleMXBean {
    public javax.management.ObjectName getSchemaService();

    public void setSchemaService(javax.management.ObjectName schemaService);

}
