/*
* Generated file
*
* Generated from: yang module name: kitchen-service-impl yang module local name: kitchen-service
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:25:29 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.kitchen_service.impl;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:config:kitchen-service:impl?revision=2014-01-31)kitchen-service", osgiRegistrationType = org.opendaylight.controller.sample.kitchen.api.KitchenService.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:kitchen-service:impl", revision = "2014-01-31", localName = "kitchen-service")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:kitchen-service:impl", revision = "2014-01-31", name = "kitchen-service-impl")

public interface KitchenServiceServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
