/*
* Generated file
*
* Generated from: yang module name: opendaylight-md-sal-binding yang module local name: binding-notification-service
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:24:36 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.binding;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding?revision=2013-10-28)binding-notification-service", osgiRegistrationType = org.opendaylight.controller.sal.binding.api.NotificationProviderService.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding", revision = "2013-10-28", localName = "binding-notification-service")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding", revision = "2013-10-28", name = "opendaylight-md-sal-binding")

public interface NotificationProviderServiceServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
