/*
* Generated file
*
* Generated from: yang module name: opendaylight-md-sal-dom yang module local name: dom-async-data-broker
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jun 16 12:24:50 CST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.dom;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom?revision=2013-10-28)dom-async-data-broker", osgiRegistrationType = org.opendaylight.controller.md.sal.dom.api.DOMDataBroker.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom", revision = "2013-10-28", localName = "dom-async-data-broker")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom", revision = "2013-10-28", name = "opendaylight-md-sal-dom")

public interface DOMDataBrokerServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
